[auth]
username = "admin"
password = "mmo888"

[github]
token = "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"  # Dán token bạn vừa copy ở Bước 1
repo_name = "321lamkiet/tiktok-farm-data" # VD: nguyenvanA/tiktok-farm-data
branch = "main"
